# Generated by Django 4.1.4 on 2022-12-24 03:53

import Www.apps.blog.models
import ckeditor_uploader.fields
from django.db import migrations, models
import meta.models
import pictures.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Name')),
                ('slug', models.SlugField(max_length=120, unique=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Category',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True, verbose_name='Title')),
                ('slug', models.SlugField(help_text='URLs for SEO. It is completed automatically.', max_length=200, unique=True, verbose_name='News URL')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Description')),
                ('preview_image', pictures.models.PictureField(aspect_ratios=[None], blank=True, breakpoints={'l': 1200, 'm': 992, 's': 768, 'xl': 1400, 'xs': 576}, container_width=1200, file_types=['WEBP'], grid_columns=12, pixel_densities=[1, 2], upload_to=Www.apps.blog.models.image_path, verbose_name='Cover Image')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Post Content')),
                ('to_post', models.BooleanField(default=False, verbose_name='To Post?')),
                ('visits', models.IntegerField(default=0)),
                ('publish_on', models.DateTimeField(blank=True, null=True, verbose_name='Publication Date')),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Posts',
                'verbose_name_plural': 'Posts',
                'ordering': ['-created_on'],
            },
            bases=(meta.models.ModelMeta, models.Model),
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('slug', models.SlugField(max_length=120, unique=True)),
            ],
        ),
    ]
